export type ApplicationErrorCode =
  | 'VALIDATION_FAILED'
  | 'IMAGE_INVALID'
  | 'STORAGE_UNAVAILABLE'
  | 'STORAGE_QUOTA_EXCEEDED'
  | 'MONSTER_NOT_FOUND'
  | 'BATTLE_INVALID'
  | 'OPERATION_IN_PROGRESS'
  | 'UNEXPECTED';
